c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos7
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
expat:
- '2'
fontconfig:
- '2'
freetype:
- '2'
harfbuzz:
- '8'
target_platform:
- linux-armv7l
zlib:
- '1.2'
cdt_arch:
- armv7l
